### ISSUE TITLE
Add PS4/XBOX support

### ISSUE THREAD

**Issue by Flenst** [Procurement-PoE/Procurement#1013]
The get-item and get-stash-items URL needs a simple "&realm=sony" or "&realm=xbox" added, maybe with a dropdown at Login. Rest works the same. My fork only supports PS4, adding dropdown and multi platform support is beyond my capabilities ;)

**Comment by aydjay** [comment]
Do you have any api documentation that shows exactly what is needed to "Talk" to the PS4 realm?#

Adding in a mechanism as you have suggested with the UI isn't a massive piece of work but knowing exactly what has changed will help a lot.

**Comment by Flenst** [comment]
No api documentation, I looked at my network traffic in browser to find out where is the difference to the PC. The realm names are in the .js of the main site. My simple commit https://github.com/Flenst/Procurement-PS4/commit/a512c1d0717bd9be0aa530506dad7798b70bb03c makes it fully functional with PS4 accounts. Using xbox instead of sony should make it fully functional with xbox accounts.

**Comment by aydjay** [comment]
I'm a bit reluctant to implement some changes for "Undocumented" parts of the API, as there could be other messages that need to be modified for it to work correctly. I have noticed in your commit that you haven't applied the realm parameter to the other API methods: LoginURL, AccountNameURL and CharacterURL for example.

I don't own an XBox or PS4 either so testing will be tricky.

@Stickymaddness What's your opinion?

**Comment by Flenst** [comment]
Yes, those gave me the correct results without a need to specify the realm. The realm was necessary for the stash tabs and inventory tabs, at launch they threw an error without the realm specified.

**Comment by killa78** [comment]
@aydjay  I know that Openarl (Path of Building) has utilized the new API  to allow it to import from the username etc.  See [The Import Tab Code within PoB](https://github.com/Openarl/PathOfBuilding/blob/master/Classes/ImportTab.lua)

**Comment by aydjay** [comment]
This can be closed
