### ISSUE TITLE
Loading Very slow switch tabs .Very slow

### ISSUE THREAD

**Issue by Gxtro2001** [Procurement-PoE/Procurement#1016]

**Comment by Gxtro2001** [comment]
I have the lasted version but it loads very slow changing tab to tab , I cleared my history but still very slow .

**Comment by thailyn** [comment]
Hi, thanks for the report.  Is switching tabs suddenly a lot slower than it used to be, or has it always been this slow?  How slow are we talking about?  Do all tabs take the same amount of time to switch to, or do some take longer than others (e.g., those with more items)?  What do you mean when you say you cleared your history?  Also, can you attach your `DebugInfo.Log` file?  That might have some information about what is going on.

**Comment by aydjay** [comment]
I've tested this and it works absolutely fine for me.

**Comment by Gxtro2001** [comment]
Is procurement being kept up to date?
    On Wednesday, December 6, 2023 at 12:43:48 AM CST, Charles Macanka ***@***.***> wrote:  
 
 


Closed #1016 as not planned.

**Comment by thailyn** [comment]
It currently needs a few updates, but I hope to get caught up soon.

This bug was closed because it did not have any actionable information, and it has sat idle for years.
