### ISSUE TITLE
[Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by ghost** [Procurement-PoE/Procurement#1020]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3138640/DebugInfo.log)

**Comment by thailyn** [comment]
Procurement is getting 404 errors when trying to refresh some tabs.  Make sure you have a valid SessionID.  Also, if you modified your tabs (moved, renamed, added, deleted tabs), restart Procurement and enable the option to refresh all tabs on login.

**Comment by thailyn** [comment]
Closing due to age and the GitHub user has been since deleted.
