### ISSUE TITLE
Error loading stash tab

### ISSUE THREAD

**Issue by alejandromaier** [Procurement-PoE/Procurement#1024]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3266045/DebugInfo.log)

**Comment by thailyn** [comment]
According to the log, the server is returning a 429 error, which means you are going exceeding your allowed usage of the GGG API.  One instance of Procurement itself won't do this.  Are you using multiple instances of Procurement at the same time, or other apps which use your account info to access the API?
