### ISSUE TITLE
Tabs contents are stale despite refreshing

### ISSUE THREAD

**Issue by melink14** [Procurement-PoE/Procurement#1035]
After I move stuff around in my tabs procurement doesn't update. I've clicked "refresh used tabs" but it didn't help (even though it showed text that it was refreshing all of my tabs).

I also restarted the app but the old tab contents were still there. The inventory tab did eventually though.

Is there something specific I need to do to see the results of my changes in procurement? The poe website does show the right contents.

**Comment by thailyn** [comment]
Hi, this bug will be fixed by #1032.  You can download an automatically-built version of Procurement with this fix [here](https://ci.appveyor.com/api/buildjobs/9p86lq4nsx1192hf/artifacts/Procurement%2Fbin%2FProcurement.zip), if you wish.

**Comment by melink14** [comment]
Thanks. I saw that the other issue but since it also mentioned crashing I thought it was separate. Thanks!
