### ISSUE TITLE
erro 403

### ISSUE THREAD

**Issue by Luciiano** [Procurement-PoE/Procurement#1037]
This is what I get on startup of the application and try sync with my Stash tabs after making no alterations to the settings.

Procurement 1.27.1 Initialized.
                                                          
Authenticating Luccianno                                                                  

[Error] The remote server returned an error: (403) Forbidden.

**Comment by thailyn** [comment]
Hi, please provide the full error details from the `DebugInfo.log` file, or attach the file itself.  You can also try getting a fresh SessionID from logging out and back in in your browser.

**Comment by Luciiano** [comment]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3298553/DebugInfo.log)

I already left and came back several times to reset the SessionID.
