### ISSUE TITLE
Wont let me in

### ISSUE THREAD

**Issue by Xetno** [Procurement-PoE/Procurement#1047]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3363509/DebugInfo.log)
I can't login. It attempts to read my stashes and then fails.

**Comment by aydjay** [comment]
Make sure to login to the POE website and get a fresh PoeSessionId

**Comment by Xetno** [comment]
Just did that, tells me the same thing. added log, from after trying. 
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3363674/DebugInfo.log)

**Comment by Xetno** [comment]
Did it one more time today, refreshed the ID by logging in and out. Now. Same thing, can't get in 
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3367857/DebugInfo.log)

**Comment by aydjay** [comment]
I've double-checked your debuginfo.log

I'm assuming that you are a PS4 player as you are logging into the PS4 realm, is this what you were intending to do? Make sure you have the correct realm selected.

**Comment by Xetno** [comment]
Yeah. I am, I logged into the website with my ps4 login, fetched the SessionID, and then entered ps4 in the program. Am I in the wrong here or?

**Comment by aydjay** [comment]
The only other thing I can think is that you are requesting "Standard" league data. I don't know how the leagues mechanics work on the console realms so make sure you create a dummy character on standard and put "Something" in the stash.

I developed the console support blind as I don't own any consoles.

**Comment by Xetno** [comment]
Hmm.. I could try and make one at standard, but my current toon on pathofexile.com is listed in the current league. The software doesn't provice an option to choose between standard and current league. The requesting standard stash part it does on it's own. I've done nothing else but fet the session ID from the legaue toon, and insert my psn..

**Comment by Xetno** [comment]
Update: 

It worked just fine on my PC account, still not on my ps4 account. 
Sadly i'm not using my pc account this league. :D

**Comment by aydjay** [comment]
You can change the league it connects to by editing the settings.xml file.

![image](https://user-images.githubusercontent.com/9460838/60820279-0ce65280-a199-11e9-8563-f0ca954c3411.png)

Look around line 86 in the application folder

**Comment by Xetno** [comment]
Tried that. Didn't work either. 
Even refreshed the sessionID and all that. Still nothing. The idea of removing the other leagues was a good idea though, but even so, it still crashes at the same place.

**Comment by aydjay** [comment]
That is curious, can you pass me your latest debuginfo.log and if you have any "Bin" files in your "AccountName" folder that would be much appreciated

**Comment by Xetno** [comment]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3386633/DebugInfo.log)

it wont let me attach the characterdata.bin files, which are the only bin files that I have. 
Also, sry for the late answer. Life happened :D

**Comment by Xetno** [comment]
[characterdata.txt](https://github.com/Stickymaddness/Procurement/files/3386805/characterdata.txt)

Hmm, after converting it to .txt and reading it. It appears that it's fetching the toon I have on standard called XetLul, while still saying it's going for league legion. The only toon I have currently have in the league is called Xetstab.
