### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YaProstoUmniy** [Procurement-PoE/Procurement#1121]
![Screenshot_26](https://user-images.githubusercontent.com/72607883/95577822-8a071400-0a3b-11eb-91c2-cc2b738f0ffc.jpg)

**Comment by SomeNameIDunno** [comment]
I believe I have the same issue

**Comment by thailyn** [comment]
Thanks for the report.  Can you attach your `DebugInfo.log` file?  That will have more details about the issue.  Also, what were you doing when the error happened?

**Comment by YaProstoUmniy** [comment]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/5356302/DebugInfo.log)

**Comment by thailyn** [comment]
The `DebugInfo.log` file doesn't give much information, which suggest the error is happening soon after Procurement starts.  I can't replicate the issue, however.  What are you doing when the error happens?  If you can attach the `.bin` files for your account, that would help, too.

**Comment by thailyn** [comment]
I realized this is probably the same issue as in #1117.  Please test out the patch I wrote to fix this, available [here](https://github.com/Stickymaddness/Procurement/issues/1117#issuecomment-698026185). (This PR was approved and merged, but there is no new Procurement version released yet.)

**Comment by SomeNameIDunno** [comment]
The fix works
