### ISSUE TITLE
Failed to build https request 

### ISSUE THREAD

**Issue by Arizse** [Procurement-PoE/Procurement#1132]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/7148919/DebugInfo.log)

**Comment by thailyn** [comment]
Procurement here is failing to retrieve one of your stash tabs (it's getting a 404 error).  This is an error that's been reported periodically, but I haven't been able to track down the cause.  Can you try to scan your stash tabs again?  It has been a transient error in the past.

**Comment by Arizse** [comment]
scanned again here is the new debuginfo 
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/7156389/DebugInfo.log)

**Comment by thailyn** [comment]
Hm.  Same error again.  Procurement is trying to get the first stash tab for the Standard league for the Xbox realm.  Have you played in that league before (in other words, does a stash exist for your account there)?

Is this error happening when you are trying to log in to the Procurement app?  Do you have the "refresh on login" option enabled or disabled?

**Comment by Arizse** [comment]
it is happening when i am trying to login regardless if refresh on login is enabled or not

**Comment by thailyn** [comment]
What platform(s) do you play PoE on?  The failing query is for Xbox; do you play on there?

**Comment by Arizse** [comment]
yes

**Comment by thailyn** [comment]
Have you been able to successfully log in with Procurement before?

Please make sure your Session ID is still valid.

Do you need to download your stash tabs for Standard?  If you are not [currently] playing in that league, we can try to get around this error by editing the Procurement settings to skip the Standard league.  If you have previously downloaded the stash tabs for the league you want to use Procurement with (e.g., Expedition), you should be able to choose the "Offline" button when logging in to Procurement.  From there, you can go to the Settings tab, check "Download Only Selected Leagues", and then check the boxes next to the leagues you want to use Procurement with.  Unselected leagues (e.g., Standard) will not have their tabs downloaded, avoiding the error you're encountering.

If you haven't downloaded the stash for the leagues you want to use Procurement with, you will need to edit the `Settings.xml` file manually.  This file is in the same directory as `Procurement.exe`.  In this file, in the `<UserSettings>` section, edit the line with the "DownloadOnlyMyLeagues" setting to be

```xml
    <Setting name="DownloadOnlyMyLeagues" value="True" />
```

If a line with that setting does not exist, add one in the `<UserSettings>` section.

Then, in the `<Lists>` section, edit the list for `MyLeagues` so it includes the leagues you want to download stashes for. (Or add such a list if one does not already exist.) For example, if you want to use Procurement with the Expedition league, add the following:

```xml
    <List name="MyLeagues">
      <Item value="Expedition" />
    </List>
```

**Comment by thailyn** [comment]
Hi, @Arizse , were you able to log in using one of my workarounds?

**Comment by thailyn** [comment]
Please reopen or file a new issue if you are still having problems.  Thanks!
