### ISSUE TITLE
i can't login

### ISSUE THREAD

**Issue by md3848** [Procurement-PoE/Procurement#1133]
for **Session-ID** i add this code :
![0](https://user-images.githubusercontent.com/17591943/134669229-cd86f1f7-d3f8-4d30-a934-a32324c667f4.PNG)
and for **Alias** i test 1 time my poe-acc-name and next time my hero name next time random text, 100 time until now i test, show this message :
`[Error] Cloud flare clearance failed, please wait one minute and try again`
what i do? what is my problem?
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/7225397/DebugInfo.log)

**Comment by thailyn** [comment]
Hey, thanks for using Procurement.  When logging in with a Session-ID, you should provide the name used when logging in to pathofexile.com.  I expect this would be the email address of the account in almost all cases.

Moreover, there is an issue with the latest release of Procurement with Cloudflare.  I haven't tested it, but there is a fork with a patch for this bug described [here](https://github.com/Stickymaddness/Procurement/issues/1128#issuecomment-758872178).  I can also work on creating a PR this weekend with a fix for this.

**Comment by md3848** [comment]
ty, now i use my email, with "@gmail.com" and without "@gmail.com", again show last error.

**Comment by CobaltLupine** [comment]
> Hey, thanks for using Procurement. When logging in with a Session-ID, you should provide the name used when logging in to pathofexile.com. I expect this would be the email address of the account in almost all cases.
> 
> Moreover, there is an issue with the latest release of Procurement with Cloudflare. I haven't tested it, but there is a fork with a patch for this bug described [here](https://github.com/Stickymaddness/Procurement/issues/1128#issuecomment-758872178). I can also work on creating a PR this weekend with a fix for this.

Hey there, was there ever any update for the Cloudflare issue? It's still happening.
