### ISSUE TITLE
Error debuglog

### ISSUE THREAD

**Issue by spunkerms** [Procurement-PoE/Procurement#1140]
Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
![imagem_2022-07-01_005433104](https://user-images.githubusercontent.com/108506320/176820255-f79ab448-adb7-4e35-9ec6-db3e2cb1a8d7.png)

Please, help me with this issue ?

**Comment by thailyn** [comment]
Hey, thanks for the report.  Please include your DebugInfo.log file, so we can see what the issue is.

**Comment by mikenik4** [comment]
Looks like I have the same problem and it also started happening only recently, maybe my log with error will be helpful
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9032852/DebugInfo.log)

**Comment by CoutoSH** [comment]
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9035739/DebugInfo.log)

same is happening to me, here more data if u guys need.

**Comment by PabloAlarco** [comment]
I have this same issue happening since several days ago. Any news about it?

**Comment by PaloCerezo95** [comment]
same problem 
DebugInfo.log

**Comment by GunsnrosesHG** [comment]
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9420155/DebugInfo.log)
same here

**Comment by GunsnrosesHG** [comment]
> I have this same issue happening since several days ago. Any news about it?

did you find a solution ?

**Comment by chrlsfrmg** [comment]
managed to solve?

**Comment by GunsnrosesHG** [comment]
Hey no i didn't

**Comment by thailyn** [comment]
My apologies for not following up for a while.  To confirm, this is not working in the [1.29.1](https://github.com/Procurement-PoE/Procurement/releases/tag/1.29.1) version, as well? I'll take a closer look ASAP.

**Comment by Omga4000** [comment]
@thailyn @GunsnrosesHG @chrlsfrmg 
I didn't think there's still demand for the program.
I've cloned this repository and (temporarily) fixed the issue. Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by thailyn** [comment]
I have a pre-release of Procurement version 1.29.2 available [here](https://github.com/Procurement-PoE/Procurement/releases/tag/1.29.2). Please try it out and let me know if the login issues are resolved.

**Comment by CoutoSH** [comment]
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/11236426/DebugInfo.log)
same error, crucible league

**Comment by thailyn** [comment]
Hi, @CoutoSH , thanks for the report. Your error is different. In your case, Procurement is trying to send too many requests (beyond what GGG allows per minute).  This shouldn't happen when using Procurement alone, but things can get complicated. What were you doing in Procurement when you got the error?

Are you getting the same error each time you run Procurement? Please wait at least 2 minutes since you got your last error before trying with a new instance of Procurement.

Are you using other apps at the same time which use GGG's API? Procurement only tracks its own usage, so it will not always smoothly handle having a lower quota than expected.

**Comment by CoutoSH** [comment]
> Hi, @CoutoSH , thanks for the report. Your error is different. In your case, Procurement is trying to send too many requests (beyond what GGG allows per minute). This shouldn't happen when using Procurement alone, but things can get complicated. What were you doing in Procurement when you got the error?
> 
> Are you getting the same error each time you run Procurement? Please wait at least 2 minutes since you got your last error before trying with a new instance of Procurement.
> 
> Are you using other apps at the same time which use GGG's API? Procurement only tracks its own usage, so it will not always smoothly handle having a lower quota than expected.

Sorry for taking so long to reply...

it worked, I think that the problem was me and my brother trying to do stuff at the same time. the API doesn't like when we do searches and use it at the same time.

thx, and its working fine, my bad
