### ISSUE TITLE
Procurement 1.29.1  Error downloading account name

### ISSUE THREAD

**Issue by GunsnrosesHG** [Procurement-PoE/Procurement#1142]
[Error] Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

**Comment by GunsnrosesHG** [comment]
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9429777/DebugInfo.log)

**Comment by Omga4000** [comment]
Duplicate: #1140

**Comment by Omga4000** [comment]
I've cloned this repository and (temporarily) fixed the issue.
Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by GunsnrosesHG** [comment]
Thanks a lot for your help i'll check it out after work

**Comment by Omga4000** [comment]
@GunsnrosesHG 

Please try the latest release. It contains a new fix which should work permanently.
https://github.com/Omga4000/Procurement/releases/

**Comment by thailyn** [comment]
Duplicate of #1140.
