### ISSUE TITLE
Error dowloading account name

### ISSUE THREAD

**Issue by DeeDeeDaa** [Procurement-PoE/Procurement#1143]
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9542128/DebugInfo.log)

**Comment by Omga4000** [comment]
Duplicate: #1140

**Comment by chrlsfrmg** [comment]
managed to solve?

**Comment by Omga4000** [comment]
I've cloned this repository and (temporarily) fixed the issue.
Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by thailyn** [comment]
Duplicate of #1140.
