### ISSUE TITLE
Error downloading account name plis

### ISSUE THREAD

**Issue by dequer666** [Procurement-PoE/Procurement#1144]
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/9956195/DebugInfo.log)

**Comment by chrlsfrmg** [comment]
managed to solve?

**Comment by Omga4000** [comment]
I've cloned this repository and (temporarily) fixed the issue.
Feel free to download the new version I've created from my own repository, it should be public.

https://github.com/Omga4000/Procurement/releases/tag/1.30.0

Let me know if that works for you.

**Comment by Omga4000** [comment]
Please try the latest release. It contains a new fix which should work permanently.
https://github.com/Omga4000/Procurement/releases/

**Comment by thailyn** [comment]
Duplicate of #1140.
