### ISSUE TITLE
[Error] Cloud flare clearance failed, please wait one minute and try again

### ISSUE THREAD

**Issue by JusticeCother** [Procurement-PoE/Procurement#1145]
[Error] Cloud flare clearance failed, please wait one minute and try again

I'm not sure how closely this tool is being updated anymore, but I was curious if there was a fix for this?

Thank you for any help.

**Comment by thailyn** [comment]
Please test the [1.29.2](https://github.com/Procurement-PoE/Procurement/releases/tag/1.29.2) release and let me know if it is working for you again.  Thanks!
